In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity='all'
import pandas as pd
train = pd.read_csv('https://classes.soe.ucsc.edu/cmps242/Spring18/hw/hw3/train.csv',encoding='latin')
test =  pd.read_csv('https://classes.soe.ucsc.edu/cmps242/Spring18/hw/hw3/test.csv',encoding='latin')
#train.head()
test.head()
#train.sms.values


label                                                sms
0   ham                        Not..tel software name..   
1  spam  As a SIM subscriber, you are selected to recei...
2   ham  Sorry i cant take your call right now. It so h...
3  spam  Congrats! Nokia 3650 video camera phone is you...
4   ham                  No chikku nt yet.. Ya i'm free

In [52]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
corpus = [ 'This is the first document.',
     'This is the second second document.',
     'And the third one.',
     'Is this the first document?']
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names()
X.toarray()
vectorizer.vocabulary_.get('document')
train_vector  = vectorizer.fit_transform(train.sms.values)
train_vector.toarray()

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 2, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]], dtype=int64)

1

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [30]:
# preserve local ordering information by 2-grams 
bigram_vectorizer = CountVectorizer(ngram_range=(1,4),token_pattern=r'\b\w+\b',
                                   min_df=1)
analyzer = bigram_vectorizer.build_analyzer()
analyzer('Bi-grams are cool!')
X_2 = bigram_vectorizer.fit_transform(corpus).toarray()
bigram_vectorizer.get_feature_names()
X_2
X_2[:,bigram_vectorizer.vocabulary_.get('is this')]

['bi',
 'grams',
 'are',
 'cool',
 'bi grams',
 'grams are',
 'are cool',
 'bi grams are',
 'grams are cool',
 'bi grams are cool']

['and',
 'and the',
 'and the third',
 'and the third one',
 'document',
 'first',
 'first document',
 'is',
 'is the',
 'is the first',
 'is the first document',
 'is the second',
 'is the second second',
 'is this',
 'is this the',
 'is this the first',
 'one',
 'second',
 'second document',
 'second second',
 'second second document',
 'the',
 'the first',
 'the first document',
 'the second',
 'the second second',
 'the second second document',
 'the third',
 'the third one',
 'third',
 'third one',
 'this',
 'this is',
 'this is the',
 'this is the first',
 'this is the second',
 'this the',
 'this the first',
 'this the first document']

array([[0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 2, 1, 1, 1, 1,
        0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1]], dtype=int64)

array([0, 0, 0, 1], dtype=int64)

In [37]:
from sklearn.feature_extraction.text import TfidfTransformer
transformer = TfidfTransformer(smooth_idf = False)
transformer
counts=[[3,0,1],
       [2,0,0],
       [3,0,0],
       [4,0,0],
       [3,2,0],
       [3,0,2]]
tfidf = transformer.fit_transform(counts)
#tfidf.toarray()
transformer = TfidfTransformer()
transformer.fit_transform(counts).toarray()
#transformer.idf_
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectorizer.fit_transform(corpus)

TfidfTransformer(norm='l2', smooth_idf=False, sublinear_tf=False,
         use_idf=True)

array([[0.85151335, 0.        , 0.52433293],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.55422893, 0.83236428, 0.        ],
       [0.63035731, 0.        , 0.77630514]])

<4x9 sparse matrix of type '<class 'numpy.float64'>'
	with 19 stored elements in Compressed Sparse Row format>